### ISSUE TITLE
link career descripcion

### ISSUE THREAD

**Issue by GregorHak** [simulacrum-1/wfrp4e-laws-pet-shoppe#2]
Hey, can I link career descripcion like Moo Man did this for all career?
![obraz](https://user-images.githubusercontent.com/99994770/163686586-a549d560-465d-4e05-8153-2cef1a4a43fd.png)
![obraz](https://user-images.githubusercontent.com/99994770/163686601-ada7828a-4bfe-45f7-9bdd-2daf0c8b18f6.png)

Also I assume that by mistake all three descripcions have wrong (empty space) text formating. Unless it is intentional?
![obraz](https://user-images.githubusercontent.com/99994770/163686627-fcea17d5-bb7a-4da7-9e84-47eb86d4be20.png)

Anyway, thanks for the great module!

**Comment by simulacrum-1** [comment]
Hi Gregor,
That’s a good idea I’ll add those links as @mooman has.
I’ll check the text descriptions. You are probably right text formatting is unintentional.
Thanks for the feedback glad you are enjoying the module.

**Comment by GregorHak** [comment]
:)
*So as not to create a new thread I'm gonna ask here
How do you interpret trait "Tracker (2)" - some dogs (like Gobhound) has it. I see that effects tab is empty. Does Andy Law explained it? Or you have a way? Originally, this talent shouldn't have levels.

**Comment by simulacrum-1** [comment]
Good spot. Andy wrote the article in a day so there may be inconsistencies with the rule system. I would say it stacks. So Tracker (2) would add SL equal to twice their Initiative Bonus to all Track Tests.

**Comment by GregorHak** [comment]
Ok so I edit trait Tracker - effect-Prefill dialog to work like you say: "would add SL equal to twice their Initiative Bonus to all Track Tests". So now when you have Initiative Bonus = 4, and trait Tracker (3) this efect automatic add you +12 SL to all Track test. Now in details of Tracker trait you set lvl of that trait.

effect-Prefill dialog:
```
if (args.type == "skill" &&  args.item.name.includes("Track"))
{
   let sl = this.actor.characteristics.i.bonus*(this.item.specification.value || 1)
   args.prefillModifiers.slBonus += sl;
}
```
And some screens
![obraz](https://user-images.githubusercontent.com/99994770/163802880-571a9e46-3118-42f2-bfad-a41f51adfc9b.png)
![obraz](https://user-images.githubusercontent.com/99994770/163803016-b4bda0d3-1126-4901-82b8-b878e98735f3.png)
![obraz](https://user-images.githubusercontent.com/99994770/163804956-53cdb766-80b7-4c14-83dc-02291fae4aa5.png)

**Comment by simulacrum-1** [comment]
Hey that's great.

**Comment by simulacrum-1** [comment]
I just looked at Tracker (2) +10SL for a Gobhound that's very high. Perhaps he intended it to work like a mix of Talents and Traits. Where Traits tend to give you + Characteristic Bonus SL, whereas Talents +1SL per advance. I'll write to ask him though it may take a while for a reply. Perhaps he intended it to be + Characteristic Bonus SL + 1SL per advance after the first.
So using your example
So now when you have Initiative Bonus = 4, and trait Tracker (3) this effect automatic add you **+6 SL** to all Track test.
I think I use this for now till I get a reply.
