### ISSUE TITLE
Trained* description is not updated

### ISSUE THREAD

**Issue by GregorHak** [simulacrum-1/wfrp4e-laws-pet-shoppe#3]
Trained* trait description from compendium is not updated. Because - old Calm rules and have no Pointer specialization
![obraz](https://user-images.githubusercontent.com/99994770/163694020-b4230c0e-4fa6-441b-9d09-cb86777c2e35.png)
![obraz](https://user-images.githubusercontent.com/99994770/163694024-236c9f99-ca7c-45dc-9c70-22497f630162.png)

**Comment by simulacrum-1** [comment]
Hi Gregor,

The pointer specialisation wasn’t included in the original trained list Andy had in his article.
- Pointer - The animal is trained to spot birds and small game such as rabbits and 'point' to them by freezing and aiming their muzzle towards them.

I’ll add it. Basically you get to use your animals perception for hunting.

That’s strange I though I’d updated all instances of the Calm rule. I’ll fix it.

thanks again

**Comment by GregorHak** [comment]
Hey again! I just spotted that Bestiary (Law's Pure Breeds) is missing STIRLAND FIGHTING DOG, 
*He is in Trappings (Law's Pure Breeds), so is missing only in bestiary.

**Comment by simulacrum-1** [comment]
Well spotted. I’m back from bank holiday tomorrow so will make all your updates over the next few days

**Comment by GregorHak** [comment]
Do not rush. Now I think maybe it's intentional that it's not there? Becouse Note on Andy Law blog: "this is the breed in the WFRP Starter Set". But Ulzhammer Shepherd Dog from Enemy in Shadows is in bestiary.
Edit: Also in bestiary Telland Pit Bull has description copy from Bärenbiter
