### ISSUE TITLE
Horse/Mule/Pony etc Icons appear to be missing

### ISSUE THREAD

**Issue by Dono1979** [simulacrum-1/wfrp4e-laws-pet-shoppe#4]
Hello, just installed the latest version of the module and the image links to nearly all of the horses/mules/pony beasts are hitting errors. I also can't see the files in the Icons folder at all. Is there something which I have missed and can relink them in some way please?

**Comment by Dono1979** [comment]
Sorry also wanted to mention that I am happy to create image for those missing entries if you have a templated format which you use? I am no good at coding things but I can normally knock up images reasonably fast.

**Comment by simulacrum-1** [comment]
Hi, Do you have the Enemy in Shadows module installed? It's intended as an expansion to that module. So it references all the animal images from that.

**Comment by Dono1979** [comment]
Ahhh my apologies then. No we dont have that module as we play a custom campaign and weren't interest in the Enemy Within series. I will hunt down some images and manually update them, thanks for the quick response!

**Comment by Dono1979** [comment]
Also, still happy to help if you need some data entry slaves for Liber - Rhya's Gift (the potion one), very keen to see that one

**Comment by simulacrum-1** [comment]
Hi, Because the Enemy in Shadows Companion expands on the rules for mounts and animals it seemed to make sense to tie it in with that. Yeah feel free to adds some of your own icons. There is a generic Dog and Horse icon in the core rules you could link to.

**Comment by simulacrum-1** [comment]
I think I'll do Petty Piety next as it's the second volume. Some of it had been added to a module that is no longer supported and it is pretty small so should be quick to finish. There is no new equivalent yet where as there are new rules for Potion making in Winds of Magic and Tides of War was the basis for the new Battle rules in Up in Arms. But I'll get in touch when I get to it.
